### PR TITLE
Install CuTeDSL into JAX containers and remove old CuTeDSL + JAX project

### PR DESCRIPTION
**Pull request by mgoldfarb-nvidia**
CuTeDSL + JAX is now formally a part of CuTeDSL in the `cutlass.jax` sub-module. Users can now install directly from the official CuTeDSL release https://pypi.org/project/nvidia-cutlass-dsl/. Examples and documentation can be found at https://github.com/NVIDIA/cutlass/tree/main

### CODE REVIEW

File: .github/container/Dockerfile.jax [hunk 1]
```diff
@@ -142,6 +142,9 @@ COPY nsys_jax/ ${SRC_PATH_NSYS_JAX}
 ADD install-nsys-jax.sh /usr/local/bin
 RUN install-nsys-jax.sh ${SRC_PATH_NSYS_JAX}
 
+## nvidia-cutlass-dsl
```
Comment (gpupuck) [inline .github/container/Dockerfile.jax]: Can you move these two lines to above section around L136?

Comment (mgoldfarb-nvidia) [reply .github/container/Dockerfile.jax]: Done.

File: .github/eks-workflow-files/jax-cutlass/scripts/unittest.sh [hunk 2]
```diff
@@ -29,6 +16,11 @@
           nvidia-cuda-mps-control -d
 
           export PYTHONPATH=${CUTLASS_EXAMPLES_ROOT}
-          pytest-xdist.sh ${NGPUS} 1 ${LOG_DIR}/pytest-report.jsonl pytest -xsv --log-file=${LOG_DIR}/pytest_log.log --log-file-level=INFO ${PIP_SRC}/tests/ | tee -a ${LOG_DIR}/pytest_stdout_dist.log
+
+          # Run the examples
+		  for f in ${CUTLASS_ROOT}/examples/python/CuTeDSL/jax/*.py; do
```
Comment (gpupuck) [inline .github/eks-workflow-files/jax-cutlass/scripts/unittest.sh]: simply using `CUTLASS_EXAMPLES_ROOT` here? Also, these python scripts are not under pytest?

Comment (mgoldfarb-nvidia) [reply .github/eks-workflow-files/jax-cutlass/scripts/unittest.sh]: Ack `CUTLASS_EXAMPLES_ROOT`. The public facing examples are not pytests but do have result verification so if they complete we can assume the instal is alive and well. We can add more testing internally as needed.

File: .github/eks-workflow-files/jax-cutlass/scripts/unittest.sh [hunk 3]
```diff
@@ -29,6 +16,11 @@
           nvidia-cuda-mps-control -d
 
           export PYTHONPATH=${CUTLASS_EXAMPLES_ROOT}
-          pytest-xdist.sh ${NGPUS} 1 ${LOG_DIR}/pytest-report.jsonl pytest -xsv --log-file=${LOG_DIR}/pytest_log.log --log-file-level=INFO ${PIP_SRC}/tests/ | tee -a ${LOG_DIR}/pytest_stdout_dist.log
+
+          # Run the examples; if they complete then everything is working.
+		  for f in ${CUTLASS_EXAMPLES_ROOT}/jax/*.py; do
+		    echo "[Executing] $f"
+		  	python $f
```
Comment (olupton) [inline .github/eks-workflow-files/jax-cutlass/scripts/unittest.sh]: Without `-e` or explicit exit code handling, this isn't going to report any failures.
Also, without the `.jsonl` file the attempt to generate a status badge will not work.
Maybe just count failures/successes, save them in some trivial format and plumb that through instead?

File: .github/eks-workflow-files/jax-cutlass/scripts/unittest.sh [hunk 4]
```diff
@@ -29,6 +16,11 @@
           nvidia-cuda-mps-control -d
 
           export PYTHONPATH=${CUTLASS_EXAMPLES_ROOT}
-          pytest-xdist.sh ${NGPUS} 1 ${LOG_DIR}/pytest-report.jsonl pytest -xsv --log-file=${LOG_DIR}/pytest_log.log --log-file-level=INFO ${PIP_SRC}/tests/ | tee -a ${LOG_DIR}/pytest_stdout_dist.log
+
+          # Run the examples; if they complete then everything is working.
+		  for f in ${CUTLASS_EXAMPLES_ROOT}/jax/*.py; do
+		    echo "[Executing] $f"
```
Comment (olupton) [inline .github/eks-workflow-files/jax-cutlass/scripts/unittest.sh]: It looks like this is a mix of tab/space indentation, which is probably causing the CI error...

Comment (mgoldfarb-nvidia) [reply .github/eks-workflow-files/jax-cutlass/scripts/unittest.sh]: Fixed the formatting. I can't recall why everything is spaced over like it is but there was a reason I think because we copied this originally from other tests.

File: .github/eks-workflow-files/jax-cutlass/scripts/unittest.sh (hunk 3 above)
Comment (mgoldfarb-nvidia) [reply .github/eks-workflow-files/jax-cutlass/scripts/unittest.sh]: Thanks- I updated to generate a `.jsonl` to keep things the same.

**Review by olupton — DISMISSED** [review]
LGTM, I think the tests all failed because of a JAX-side bug fixed by https://github.com/jax-ml/jax/pull/36185

**Comment by mgoldfarb-nvidia** [comment]
> Ready to merge?

Appears the tests are failing for some reason:

```
=== /jax-cutlass-src/cutlass/examples/python/CuTeDSL/jax/cutlass_call_basic.py ===
Traceback (most recent call last):
  File "/jax-cutlass-src/cutlass/examples/python/CuTeDSL/jax/cutlass_call_basic.py", line 33, in <module>
    import cutlass
  File "/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/jax/types.py", line 65, in <module>
    @jax.tree_util.register_dataclass
     ^^^^^^^^^^^^^
AttributeError: module 'jax' has no attribute 'tree_util'
```

This is surprising since `jax.tree_util.register_dataclass` is a valid module inside jax.

**Comment by olupton** [comment]
> > Ready to merge?
> 
> Appears the tests are failing for some reason:
> 
> ```
> === /jax-cutlass-src/cutlass/examples/python/CuTeDSL/jax/cutlass_call_basic.py ===
> Traceback (most recent call last):
>   File "/jax-cutlass-src/cutlass/examples/python/CuTeDSL/jax/cutlass_call_basic.py", line 33, in <module>
>     import cutlass
>   File "/usr/local/lib/python3.12/dist-packages/nvidia_cutlass_dsl/python_packages/cutlass/jax/types.py", line 65, in <module>
>     @jax.tree_util.register_dataclass
>      ^^^^^^^^^^^^^
> AttributeError: module 'jax' has no attribute 'tree_util'
> ```
> 
> This is surprising since `jax.tree_util.register_dataclass` is a valid module inside jax.

I suspect it's because `PYTHONPATH=${CUTLASS_EXAMPLES_ROOT}` puts a directory containing a `jax` folder first in the path.

**Comment by gpupuck** [comment]
Anything left?

**Comment by mgoldfarb-nvidia** [comment]
> Anything left?

Sorry this is dragging out I keep switching to other high priority streams. Everything is good except this one multi-device test. I did manage to pull the container and run locally but it had no issues. For whatever reason the test appears to segfault in this environment.

We could allow it in and continue trying to debug- if there is any recommendation how to replicate the environment beyond using the container I'm open.

**Review by olupton — APPROVED** [review]
